version: '3.8'
services:
    littimeline:
        container_name: litter
        build:
            context: .
        restart: always
        tty: true
        ports: 
            -   "3000:3000"
            -   "3001:5173"
        command: ["/bin/bash"]
        working_dir: /LitTimeline

