USE litter;

CREATE TABLE
    users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id VARCHAR(255) NOT NULL UNIQUE,
        is_deleted BOOLEAN DEFAULT FALSE,
        name VARCHAR(255) NOT NULL,
        password VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE
    posts(
        id INT AUTO_INCREMENT PRIMARY KEY,
        post_id BINARY(16) DEFAULT (UUID_TO_BIN(UUID())) NOT NULL UNIQUE;
        user_id VARCHAR(255) NOT NULL,
        favorites INT DEFAULT 0,
        parent_post_id INT DEFAULT 0,
        is_deleted BOOLEAN DEFAULT FALSE,
        is_hidden BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
