USE litter;

CREATE TABLE
    users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id VARCHAR(255) NOT NULL UNIQUE,
        is_deleted BOOLEAN DEFAULT FALSE,
        name VARCHAR(255) NOT NULL,
        password VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
CREATE TABLE `sessions` (
	`session_id` CHAR(36) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`user_id` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`is_logged_in` TINYINT(1) NULL DEFAULT NULL,
    `last_timeline_post_id` INT NULL DEFAULT '0',
	`expire_at` TIMESTAMP NOT NULL DEFAULT ((now() + interval 30 day)),
	`created_at` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`session_id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;


CREATE TABLE `posts` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`post_id` BINARY(16) NOT NULL DEFAULT (uuid_to_bin(uuid())),
	`user_id` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`contents` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`favorites` INT NULL DEFAULT '0',
	`parent_post_id` INT NULL DEFAULT '0',
	`is_deleted` TINYINT(1) NULL DEFAULT '0',
	`is_hidden` TINYINT(1) NULL DEFAULT '0',
	`created_at` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `post_id` (`post_id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=7520
;

CREATE TABLE `followers`(
	`no` INT NOT NULL AUTO_INCREMENT,
	`followee_id` VARCHAR(255) NOT NULL COLLATE,
	`follower_id` VARCHAR(255) NOT NULL COLLATE,
	`created_at` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(`no`) USING BTREE
);

